version: "3.8"

services:
    db:
        image: postgres:15-alpine
        container_name: zenith_db_cs
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5433:5432"
        volumes:
            - postgres_data_cs:/var/lib/postgresql/data

volumes:
  postgres_data_cs: